services:
  coordinator:
    image: citusdata/citus:12.1
    container_name: citus_coordinator
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    command: postgres -c shared_preload_libraries=citus
    networks:
      - citusnet

  worker1:
    image: citusdata/citus:12.1
    container_name: citus_worker1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    command: postgres -c shared_preload_libraries=citus
    networks:
      - citusnet

  worker2:
    image: citusdata/citus:12.1
    container_name: citus_worker2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    command: postgres -c shared_preload_libraries=citus
    networks:
      - citusnet

networks:
  citusnet:
    driver: bridge
