services:
  postgres:
    image: postgres:15
    container_name: pg-server
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      # Mount host folder for persistent PostgreSQL data
      - ./pgdata:/var/lib/postgresql/data
      # Mount custom config files from host
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: >
      postgres -c config_file=/etc/postgresql/postgresql.conf
              -c hba_file=/etc/postgresql/pg_hba.conf
    networks:
      - pgnet

  client:
    image: postgres:15
    container_name: pg-client
    depends_on:
      - postgres
    command: sleep infinity
    networks:
      - pgnet

networks:
  pgnet:
    driver: bridge
