services:
  postgres:
    image: postgres:15
    container_name: pg-server
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - pgnet

  client:
    image: postgres:15
    container_name: pg-client
    depends_on:
      - postgres
    command: sleep infinity
    networks:
      - pgnet

networks:
  pgnet:
    driver: bridge
