services:
  monitor:
    image: citusdata/pg_auto_failover:demo
    environment:
      PGDATA: /tmp/pgaf
      PG_AUTOCTL_DEBUG: 1
    command: pg_autoctl create monitor --ssl-self-signed --auth trust --run
    expose:
      - 5432
    networks:
      - pgnet


  node1:
    image: citusdata/pg_auto_failover:demo
    environment:
      PGDATA: /tmp/pgaf
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: test
      PG_AUTOCTL_MONITOR: "postgresql://autoctl_node@monitor/pg_auto_failover"
    command:  pg_autoctl create postgres --ssl-self-signed --auth trust --pg-hba-lan --run
    expose:
      - 5432
    depends_on:
      - monitor
    networks:
      - pgnet


  node2:
    image: citusdata/pg_auto_failover:demo
    environment:
      PGDATA: /tmp/pgaf
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: test
      PG_AUTOCTL_MONITOR: "postgresql://autoctl_node@monitor/pg_auto_failover"
    command:  pg_autoctl create postgres --ssl-self-signed --auth trust --pg-hba-lan --run
    expose:
      - 5432
    depends_on:
      - node1
    networks:
      - pgnet



  node3:
    image: citusdata/pg_auto_failover:demo
    environment:
      PGDATA: /tmp/pgaf
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: test
      PG_AUTOCTL_MONITOR: "postgresql://autoctl_node@monitor/pg_auto_failover"
    command:  pg_autoctl create postgres --ssl-self-signed --auth trust --pg-hba-lan --run
    expose:
      - 5432
    depends_on:
      - node2
    networks:
      - pgnet



networks:
  pgnet:
