services:
  postgres:
    image: postgres:15
    container_name: pg-server
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      # Mount host folder for persistent PostgreSQL data
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - pgnet

  client:
    image: postgres:15
    container_name: pg-client
    depends_on:
      - postgres
    command: sleep infinity
    networks:
      - pgnet

networks:
  pgnet:
    driver: bridge
